The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) StdEnv
Restoring modules from user's cuda, for system: "grace-rhel7"
2018-05-07 23:42:41.089736: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING:tensorflow:From /home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Weights:  coco
Dataset:  ../../datasets/illustrations
Logs:  /gpfs/loomis/project/fas/leonard/swk2/Mask_RCNN/logs

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     2
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.9
DETECTION_NMS_THRESHOLD        0.3
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                14
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           balloon
NUM_CLASSES                    2
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001


Loading weights  /gpfs/loomis/project/fas/leonard/swk2/Mask_RCNN/mask_rcnn_coco.h5
Training network heads

Starting at epoch 0. LR=0.001

Checkpoint Path: /gpfs/loomis/project/fas/leonard/swk2/Mask_RCNN/logs/balloon20180507T2342/mask_rcnn_balloon_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/keras/engine/training.py:2087: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.
  UserWarning('Using a generator with `use_multiprocessing=True`'
ERROR:root:Error processing image {'id': 'differentialdiag002cabo_0117.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/differentialdiag002cabo_0117.jpg', 'width': 2102, 'height': 3453, 'polygons': [{'name': 'rect', 'x': 362, 'y': 885, 'width': 1142, 'height': 1477}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'hotspringsofbath00hattuoft_0009.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/hotspringsofbath00hattuoft_0009.jpg', 'width': 2027, 'height': 3192, 'polygons': [{'name': 'rect', 'x': 190, 'y': 421, 'width': 1518, 'height': 2223}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'gynecology00grav_0453.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/gynecology00grav_0453.jpg', 'width': 2329, 'height': 3708, 'polygons': [{'name': 'rect', 'x': 169, 'y': 533, 'width': 933, 'height': 834}, {'name': 'rect', 'x': 1161, 'y': 547, 'width': 933, 'height': 816}, {'name': 'rect', 'x': 617, 'y': 1987, 'width': 1021, 'height': 896}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'traitdesfistules00jobe_0373.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/traitdesfistules00jobe_0373.jpg', 'width': 2208, 'height': 3894, 'polygons': [{'name': 'rect', 'x': 69, 'y': 890, 'width': 1958, 'height': 2254}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b2130175x_0620.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b2130175x_0620.jpg', 'width': 1801, 'height': 2929, 'polygons': [{'name': 'rect', 'x': 241, 'y': 740, 'width': 1421, 'height': 992}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'newyorkpresbyter00newy_2_0024.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/newyorkpresbyter00newy_2_0024.jpg', 'width': 2870, 'height': 3820, 'polygons': [{'name': 'rect', 'x': 95, 'y': 942, 'width': 2707, 'height': 2613}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b22365977_0007.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b22365977_0007.jpg', 'width': 2642, 'height': 4292, 'polygons': [{'name': 'rect', 'x': 348, 'y': 556, 'width': 2064, 'height': 1657}, {'name': 'rect', 'x': 527, 'y': 2629, 'width': 1606, 'height': 1121}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b22365977_0007.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b22365977_0007.jpg', 'width': 2642, 'height': 4292, 'polygons': [{'name': 'rect', 'x': 348, 'y': 556, 'width': 2064, 'height': 1657}, {'name': 'rect', 'x': 527, 'y': 2629, 'width': 1606, 'height': 1121}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'nursingc89unse_0023.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/nursingc89unse_0023.jpg', 'width': 2925, 'height': 3889, 'polygons': [{'name': 'rect', 'x': 1020, 'y': 585, 'width': 1805, 'height': 1412}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21932323_0188.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21932323_0188.jpg', 'width': 1811, 'height': 2946, 'polygons': [{'name': 'rect', 'x': 271, 'y': 612, 'width': 1315, 'height': 1362}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21303502_0001_0191.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21303502_0001_0191.jpg', 'width': 1790, 'height': 3122, 'polygons': [{'name': 'rect', 'x': 297, 'y': 1011, 'width': 1085, 'height': 1029}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': '63571000R_0947.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/63571000R_0947.jpg', 'width': 1980, 'height': 3528, 'polygons': [{'name': 'rect', 'x': 496, 'y': 1502, 'width': 1083, 'height': 1582}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 's3edinburghmedical04edinuoft_0477.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/s3edinburghmedical04edinuoft_0477.jpg', 'width': 2126, 'height': 3206, 'polygons': [{'name': 'rect', 'x': 267, 'y': 320, 'width': 1355, 'height': 1165}, {'name': 'rect', 'x': 311, 'y': 1717, 'width': 1260, 'height': 1092}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'bulletinofuniver6767_0157.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/bulletinofuniver6767_0157.jpg', 'width': 1855, 'height': 2877, 'polygons': [{'name': 'rect', 'x': 541, 'y': 117, 'width': 1234, 'height': 1214}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21923978_0198.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21923978_0198.jpg', 'width': 1743, 'height': 3007, 'polygons': [{'name': 'rect', 'x': 450, 'y': 557, 'width': 876, 'height': 933}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'manualofoperativ00stim_0138.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/manualofoperativ00stim_0138.jpg', 'width': 2107, 'height': 3489, 'polygons': [{'name': 'rect', 'x': 594, 'y': 715, 'width': 919, 'height': 2072}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21303502_0001_0191.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21303502_0001_0191.jpg', 'width': 1790, 'height': 3122, 'polygons': [{'name': 'rect', 'x': 297, 'y': 1011, 'width': 1085, 'height': 1029}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'anaestheticsthei1914buxt_0281.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/anaestheticsthei1914buxt_0281.jpg', 'width': 1959, 'height': 3136, 'polygons': [{'name': 'rect', 'x': 618, 'y': 705, 'width': 540, 'height': 817}, {'name': 'rect', 'x': 1332, 'y': 1990, 'width': 369, 'height': 649}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'textbookofbotany00strauoft_0681.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/textbookofbotany00strauoft_0681.jpg', 'width': 1918, 'height': 3216, 'polygons': [{'name': 'rect', 'x': 201, 'y': 366, 'width': 1354, 'height': 2425}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b2491051x_0259.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b2491051x_0259.jpg', 'width': 2182, 'height': 3479, 'polygons': [{'name': 'rect', 'x': 134, 'y': 538, 'width': 1658, 'height': 2410}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'transactionsstud4161coll_0123.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/transactionsstud4161coll_0123.jpg', 'width': 2204, 'height': 3345, 'polygons': [{'name': 'rect', 'x': 46, 'y': 219, 'width': 2002, 'height': 1558}, {'name': 'rect', 'x': 388, 'y': 1853, 'width': 1299, 'height': 1021}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'transactamersurg26ameruoft_0566.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/transactamersurg26ameruoft_0566.jpg', 'width': 2099, 'height': 3490, 'polygons': [{'name': 'rect', 'x': 228, 'y': 498, 'width': 1795, 'height': 2417}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b28120553_0263.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b28120553_0263.jpg', 'width': 1789, 'height': 3082, 'polygons': [{'name': 'rect', 'x': 263, 'y': 64, 'width': 1310, 'height': 1099}, {'name': 'rect', 'x': 150, 'y': 1200, 'width': 681, 'height': 913}, {'name': 'rect', 'x': 1087, 'y': 1380, 'width': 614, 'height': 632}, {'name': 'rect', 'x': 986, 'y': 2158, 'width': 720, 'height': 757}, {'name': 'rect', 'x': 128, 'y': 2223, 'width': 659, 'height': 684}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'differentialdiag002cabo_0117.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/differentialdiag002cabo_0117.jpg', 'width': 2102, 'height': 3453, 'polygons': [{'name': 'rect', 'x': 362, 'y': 885, 'width': 1142, 'height': 1477}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': '101515374X2_0024.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/101515374X2_0024.jpg', 'width': 1861, 'height': 3445, 'polygons': [{'name': 'rect', 'x': 801, 'y': 385, 'width': 975, 'height': 890}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b2193311x_0654.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b2193311x_0654.jpg', 'width': 1759, 'height': 3008, 'polygons': [{'name': 'rect', 'x': 193, 'y': 95, 'width': 1369, 'height': 2708}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'iowamedicine8111iowa_0349.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/iowamedicine8111iowa_0349.jpg', 'width': 2679, 'height': 3743, 'polygons': [{'name': 'rect', 'x': 270, 'y': 252, 'width': 1968, 'height': 1315}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'newyorkpresbyter00newy_2_0021.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/newyorkpresbyter00newy_2_0021.jpg', 'width': 2878, 'height': 3820, 'polygons': [{'name': 'rect', 'x': 563, 'y': 110, 'width': 813, 'height': 802}, {'name': 'rect', 'x': 1433, 'y': 113, 'width': 677, 'height': 794}, {'name': 'rect', 'x': 2148, 'y': 102, 'width': 609, 'height': 813}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': '39002086340552.med.yale.edu_0389.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/39002086340552.med.yale.edu_0389.jpg', 'width': 1378, 'height': 2309, 'polygons': [{'name': 'rect', 'x': 112, 'y': 343, 'width': 1133, 'height': 1798}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'transactamersurg26ameruoft_0566.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/transactamersurg26ameruoft_0566.jpg', 'width': 2099, 'height': 3490, 'polygons': [{'name': 'rect', 'x': 228, 'y': 498, 'width': 1795, 'height': 2417}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21932323_0260.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21932323_0260.jpg', 'width': 1811, 'height': 2946, 'polygons': [{'name': 'rect', 'x': 782, 'y': 1881, 'width': 373, 'height': 385}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'newjerseymedicin9611medi_0202.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/newjerseymedicin9611medi_0202.jpg', 'width': 2623, 'height': 3742, 'polygons': [{'name': 'rect', 'x': 170, 'y': 571, 'width': 2397, 'height': 2808}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'differentialdiag002cabo_0463.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/differentialdiag002cabo_0463.jpg', 'width': 2041, 'height': 3441, 'polygons': [{'name': 'rect', 'x': 368, 'y': 593, 'width': 1203, 'height': 2286}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'differentialdiag002cabo_0138.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/differentialdiag002cabo_0138.jpg', 'width': 2102, 'height': 3453, 'polygons': [{'name': 'rect', 'x': 608, 'y': 885, 'width': 1114, 'height': 1470}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'gynecology00grav_0453.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/gynecology00grav_0453.jpg', 'width': 2329, 'height': 3708, 'polygons': [{'name': 'rect', 'x': 169, 'y': 533, 'width': 933, 'height': 834}, {'name': 'rect', 'x': 1161, 'y': 547, 'width': 933, 'height': 816}, {'name': 'rect', 'x': 617, 'y': 1987, 'width': 1021, 'height': 896}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21357298_0133.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21357298_0133.jpg', 'width': 1660, 'height': 2826, 'polygons': [{'name': 'rect', 'x': 115, 'y': 647, 'width': 1257, 'height': 1366}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b2150751x_0001_0585.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b2150751x_0001_0585.jpg', 'width': 2025, 'height': 3331, 'polygons': [{'name': 'rect', 'x': 937, 'y': 1200, 'width': 729, 'height': 930}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'anatomicalmemoir21good_0494.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/anatomicalmemoir21good_0494.jpg', 'width': 1680, 'height': 2929, 'polygons': [{'name': 'rect', 'x': 84, 'y': 203, 'width': 1430, 'height': 2472}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'journalofarkansa8911arka_0046.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/journalofarkansa8911arka_0046.jpg', 'width': 3402, 'height': 4569, 'polygons': [{'name': 'rect', 'x': 403, 'y': 330, 'width': 991, 'height': 1122}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'proceedings16newy_0178.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/proceedings16newy_0178.jpg', 'width': 2133, 'height': 3495, 'polygons': [{'name': 'rect', 'x': 398, 'y': 1125, 'width': 1434, 'height': 1389}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'transactionsstud4161coll_0123.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/transactionsstud4161coll_0123.jpg', 'width': 2204, 'height': 3345, 'polygons': [{'name': 'rect', 'x': 46, 'y': 219, 'width': 2002, 'height': 1558}, {'name': 'rect', 'x': 388, 'y': 1853, 'width': 1299, 'height': 1021}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21932323_0046.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21932323_0046.jpg', 'width': 1811, 'height': 2946, 'polygons': [{'name': 'rect', 'x': 557, 'y': 709, 'width': 712, 'height': 817}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'transactionso10newy_0410.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/transactionso10newy_0410.jpg', 'width': 2007, 'height': 3315, 'polygons': [{'name': 'rect', 'x': 332, 'y': 378, 'width': 811, 'height': 322}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b28120553_0263.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b28120553_0263.jpg', 'width': 1789, 'height': 3082, 'polygons': [{'name': 'rect', 'x': 263, 'y': 64, 'width': 1310, 'height': 1099}, {'name': 'rect', 'x': 150, 'y': 1200, 'width': 681, 'height': 913}, {'name': 'rect', 'x': 1087, 'y': 1380, 'width': 614, 'height': 632}, {'name': 'rect', 'x': 986, 'y': 2158, 'width': 720, 'height': 757}, {'name': 'rect', 'x': 128, 'y': 2223, 'width': 659, 'height': 684}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b29123082_0081.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b29123082_0081.jpg', 'width': 2024, 'height': 3346, 'polygons': [{'name': 'rect', 'x': 23, 'y': 788, 'width': 1988, 'height': 1534}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21303502_0001_0191.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21303502_0001_0191.jpg', 'width': 1790, 'height': 3122, 'polygons': [{'name': 'rect', 'x': 297, 'y': 1011, 'width': 1085, 'height': 1029}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'newyorkpresbyter00newy_2_0021.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/newyorkpresbyter00newy_2_0021.jpg', 'width': 2878, 'height': 3820, 'polygons': [{'name': 'rect', 'x': 563, 'y': 110, 'width': 813, 'height': 802}, {'name': 'rect', 'x': 1433, 'y': 113, 'width': 677, 'height': 794}, {'name': 'rect', 'x': 2148, 'y': 102, 'width': 609, 'height': 813}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'differentialdiag002cabo_0117.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/differentialdiag002cabo_0117.jpg', 'width': 2102, 'height': 3453, 'polygons': [{'name': 'rect', 'x': 362, 'y': 885, 'width': 1142, 'height': 1477}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b28120553_0263.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b28120553_0263.jpg', 'width': 1789, 'height': 3082, 'polygons': [{'name': 'rect', 'x': 263, 'y': 64, 'width': 1310, 'height': 1099}, {'name': 'rect', 'x': 150, 'y': 1200, 'width': 681, 'height': 913}, {'name': 'rect', 'x': 1087, 'y': 1380, 'width': 614, 'height': 632}, {'name': 'rect', 'x': 986, 'y': 2158, 'width': 720, 'height': 757}, {'name': 'rect', 'x': 128, 'y': 2223, 'width': 659, 'height': 684}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'bulletinofuniver6767_0157.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/bulletinofuniver6767_0157.jpg', 'width': 1855, 'height': 2877, 'polygons': [{'name': 'rect', 'x': 541, 'y': 117, 'width': 1234, 'height': 1214}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'principlespracti00bedf_0066.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/principlespracti00bedf_0066.jpg', 'width': 2493, 'height': 4262, 'polygons': [{'name': 'rect', 'x': 569, 'y': 2607, 'width': 1375, 'height': 1050}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21932323_0509.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21932323_0509.jpg', 'width': 1811, 'height': 2946, 'polygons': [{'name': 'rect', 'x': 198, 'y': 271, 'width': 1309, 'height': 1455}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'terramariaemedic00unse_14_0153.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/terramariaemedic00unse_14_0153.jpg', 'width': 3519, 'height': 4578, 'polygons': [{'name': 'rect', 'x': 50, 'y': 145, 'width': 1020, 'height': 1233}, {'name': 'rect', 'x': 1165, 'y': 145, 'width': 2168, 'height': 1193}, {'name': 'rect', 'x': 63, 'y': 1506, 'width': 1424, 'height': 1120}, {'name': 'rect', 'x': 1605, 'y': 1447, 'width': 1705, 'height': 1156}, {'name': 'rect', 'x': 63, 'y': 2748, 'width': 2131, 'height': 1492}, {'name': 'rect', 'x': 2304, 'y': 2744, 'width': 1048, 'height': 1483}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': '39002086340552.med.yale.edu_0389.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/39002086340552.med.yale.edu_0389.jpg', 'width': 1378, 'height': 2309, 'polygons': [{'name': 'rect', 'x': 112, 'y': 343, 'width': 1133, 'height': 1798}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b29124815_0156.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b29124815_0156.jpg', 'width': 1914, 'height': 3294, 'polygons': [{'name': 'rect', 'x': 212, 'y': 717, 'width': 1301, 'height': 1790}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b28120553_0263.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b28120553_0263.jpg', 'width': 1789, 'height': 3082, 'polygons': [{'name': 'rect', 'x': 263, 'y': 64, 'width': 1310, 'height': 1099}, {'name': 'rect', 'x': 150, 'y': 1200, 'width': 681, 'height': 913}, {'name': 'rect', 'x': 1087, 'y': 1380, 'width': 614, 'height': 632}, {'name': 'rect', 'x': 986, 'y': 2158, 'width': 720, 'height': 757}, {'name': 'rect', 'x': 128, 'y': 2223, 'width': 659, 'height': 684}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'transactionso10newy_0410.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/transactionso10newy_0410.jpg', 'width': 2007, 'height': 3315, 'polygons': [{'name': 'rect', 'x': 332, 'y': 378, 'width': 811, 'height': 322}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21357298_0133.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21357298_0133.jpg', 'width': 1660, 'height': 2826, 'polygons': [{'name': 'rect', 'x': 115, 'y': 647, 'width': 1257, 'height': 1366}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'terramariaemedic00unse_14_0128.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/terramariaemedic00unse_14_0128.jpg', 'width': 3546, 'height': 4678, 'polygons': [{'name': 'rect', 'x': 819, 'y': 875, 'width': 1018, 'height': 1301}, {'name': 'rect', 'x': 1898, 'y': 5, 'width': 1592, 'height': 2162}, {'name': 'rect', 'x': 523, 'y': 3449, 'width': 1528, 'height': 870}, {'name': 'rect', 'x': 2111, 'y': 3032, 'width': 1370, 'height': 995}, {'name': 'rect', 'x': 176, 'y': 2236, 'width': 1870, 'height': 1153}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'textbookofdental00burc_0386.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/textbookofdental00burc_0386.jpg', 'width': 1990, 'height': 3381, 'polygons': [{'name': 'rect', 'x': 107, 'y': 978, 'width': 425, 'height': 603}, {'name': 'rect', 'x': 559, 'y': 975, 'width': 422, 'height': 603}, {'name': 'rect', 'x': 985, 'y': 985, 'width': 409, 'height': 596}, {'name': 'rect', 'x': 1394, 'y': 1042, 'width': 519, 'height': 543}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'lehrbuchderspeci001strm_0639.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/lehrbuchderspeci001strm_0639.jpg', 'width': 2065, 'height': 3269, 'polygons': [{'name': 'rect', 'x': 1314, 'y': 469, 'width': 320, 'height': 414}, {'name': 'rect', 'x': 1172, 'y': 1042, 'width': 641, 'height': 1660}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'dentalcosmos5186whit_0034.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/dentalcosmos5186whit_0034.jpg', 'width': 2490, 'height': 4058, 'polygons': [{'name': 'rect', 'x': 145, 'y': 683, 'width': 996, 'height': 767}, {'name': 'rect', 'x': 1209, 'y': 546, 'width': 1145, 'height': 988}, {'name': 'rect', 'x': 76, 'y': 2149, 'width': 1161, 'height': 1028}, {'name': 'rect', 'x': 1253, 'y': 2133, 'width': 1185, 'height': 972}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'hotspringsofbath00hattuoft_0009.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/hotspringsofbath00hattuoft_0009.jpg', 'width': 2027, 'height': 3192, 'polygons': [{'name': 'rect', 'x': 190, 'y': 421, 'width': 1518, 'height': 2223}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': '2556052R_0163.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/2556052R_0163.jpg', 'width': 1995, 'height': 3194, 'polygons': [{'name': 'rect', 'x': 566, 'y': 730, 'width': 740, 'height': 990}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b2804874x_0074.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b2804874x_0074.jpg', 'width': 1603, 'height': 2493, 'polygons': [{'name': 'rect', 'x': 225, 'y': 657, 'width': 1329, 'height': 237}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'b21932323_0260.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/b21932323_0260.jpg', 'width': 1811, 'height': 2946, 'polygons': [{'name': 'rect', 'x': 782, 'y': 1881, 'width': 373, 'height': 385}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'proceedingsofann1875ameruoft_0636.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/proceedingsofann1875ameruoft_0636.jpg', 'width': 2003, 'height': 3439, 'polygons': [{'name': 'rect', 'x': 518, 'y': 1128, 'width': 1206, 'height': 1553}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
ERROR:root:Error processing image {'id': 'journalofarkansa8911arka_0046.jpg', 'source': 'balloon', 'path': '../../datasets/illustrations/train/journalofarkansa8911arka_0046.jpg', 'width': 3402, 'height': 4569, 'polygons': [{'name': 'rect', 'x': 403, 'y': 330, 'width': 991, 'height': 1122}]}
Traceback (most recent call last):
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "balloon.py", line 165, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
Epoch 1/30
Traceback (most recent call last):
  File "balloon.py", line 366, in <module>
    train(model)
  File "balloon.py", line 201, in train
    layers='heads')
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2328, in train
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/fas/leonard/swk2/miniconda3/envs/maskRCNN/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
KeyError: 'all_points_y'
